### ISSUE TITLE
Exception: Error: Invalid box type: None  

### ISSUE THREAD

**Issue by Li-Whasaka** [qcraftai/distill-bev#2]
**I RUN  THIS SCRIPT ./scripts/teacher_to_bevdepth4d/centerpoint2bevdepth.sh** 
**AND Program started successfully,BUT after the fourth epoch of training, it saved checkpoint and evaluated, then SHOWed,**
!------------------------------------------------------------------------------------------------------------------------------------------
2023-10-18 18:19:24,804 - mmdet - INFO - Saving checkpoint at 4 epochs
[                                                  ] 0/81, elapsed: 0s, ETA:/home/lwx/Desktop/lwx/distill-bev/mmdet3d/core/bbox/coders/centerpoint_bbox_coders.py:200: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.post_center_range = torch.tensor(
/home/lwx/Desktop/lwx/distill-bev/mmdet3d/core/bbox/coders/centerpoint_bbox_coders.py:200: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.post_center_range = torch.tensor(
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 3.7 task/s, elapsed: 22s, ETA:     0s
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 28180.0 task/s, elapsed: 0s, ETA:     0s
Results writes to /tmp/tmp8p63c1uy/results/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
Traceback (most recent call last):                                                                                                
  File "./tools/train.py", line 256, in <module>
    main()
  File "./tools/train.py", line 244, in main
    train_model(
  File "/home/lwx/Desktop/lwx/distill-bev/mmdet3d/apis/train.py", line 21, in train_model
    train_detector(
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 134, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 61, in train
    self.call_hook('after_train_epoch')
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 367, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/lwx/Desktop/lwx/distill-bev/mmdet3d/datasets/nuscenes_dataset.py", line 746, in evaluate
    ret_dict = self._evaluate_single(result_files[name], logger)
  File "/home/lwx/Desktop/lwx/distill-bev/mmdet3d/datasets/nuscenes_dataset.py", line 602, in _evaluate_single
    nusc_eval = NuScenesEval(
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/nuscenes/eval/detection/evaluate.py", line 94, in __init__
    self.pred_boxes = filter_eval_boxes(nusc, self.pred_boxes, self.cfg.class_range, verbose=verbose)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
    class_field = _get_box_class_field(eval_boxes)
  File "/home/lwx/anaconda3/envs/distillbev/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
    raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None
!-------------------------------------------------------------------------------------------------------------------------------------------
**I can't figure out  where the problem is.....**

**Comment by dingwenli** [comment]
The error is perhaps related to your validation data. From your message, the evaluation was performed on 81 validation samples, while the whole nuScenes validation set has 6019 samples. Please double check your validation data.

**Comment by Li-Whasaka** [comment]
> The error is perhaps related to your validation data. From your message, the evaluation was performed on 81 validation samples, while the whole nuScenes validation set has 6019 samples. Please double check your validation data.

Thank you for your reply. 
I am using a mini dataset, so must I use a full dataset? I'm not sure if it's possible to use Mini by modifying the code, as I haven't seen the relevant code yet.

**Comment by dingwenli** [comment]
We designed the data generation scripts based on the full dataset and performed all the experiments on it. I would suggest using the full dataset to avoid potential issues.

**Comment by Li-Whasaka** [comment]
> We designed the data generation scripts based on the full dataset and performed all the experiments on it. I would suggest using the full dataset to avoid potential issues.

OK,GOT IT,THANKS for your immediate help.
